// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class UntitledTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void untitled() {
    driver.get("https://www.fantasyalarm.com/nfl/projections/daily/qb/FD/All%20Games");
    driver.manage().window().setSize(new Dimension(1066, 818));
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("FanDuel")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("All Games")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(1) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(2) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(3) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(4) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(5) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(6) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(7) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".fa-download")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(8) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(9) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(10) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(11) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("DraftKings")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("All Games")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(2) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(3) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(4) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(5) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(6) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(7) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(8) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(9) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(10) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(11) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Y! Daily")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("All Games")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(1) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(2) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(3) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(4) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(5) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(6) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(7) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(8) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(9) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(10) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(11) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("CBS")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("All Games")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(1) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(2) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(3) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(4) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(5) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(6) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(7) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(8) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(9) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(10) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(11) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("ESPN")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("All Games")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(1) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(2) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(3) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(4) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(5) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(6) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(7) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(8) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(9) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(10) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(11) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Fanball")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("All Games")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(1) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(2) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(3) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(4) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(5) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(6) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(7) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(8) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(9) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(10) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(11) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("RTDaily")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("All Games")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(1) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(2) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(3) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(4) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(5) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(6) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(7) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(8) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(9) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(10) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(11) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("NFFC")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("All Games")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(1) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(2) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(3) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(4) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(5) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(6) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(7) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(8) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(9) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(10) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(11) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("FFPC")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("All Games")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(1) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(2) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(3) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(4) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(5) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(6) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(7) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(8) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(9) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(10) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(11) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("BB10")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("All Games")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(1) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(2) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(3) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(4) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(5) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(6) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(7) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(8) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(9) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(10) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(11) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("TDO")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("All Games")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(1) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(2) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(3) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(4) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(5) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(6) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(7) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(8) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(9) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(10) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(11) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("CDM")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("All Games")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(1) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(2) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(3) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(4) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(5) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(6) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(7) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(8) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(9) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(10) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(11) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("RTDM")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("All Games")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(1) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(2) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(3) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(4) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(5) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(6) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(7) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(8) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(9) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(10) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(11) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Fantrax")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("All Games")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(1) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(2) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(3) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(4) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(5) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(6) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(7) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(8) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(9) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(10) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(11) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#scoring-selector .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("H2H Weekly")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#slate-selector .dropdown-arrow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("All Games")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(1) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(2) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(3) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(4) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(5) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(6) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(7) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(8) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(9) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(10) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(11) > .bg-sport-nfl")).click();
    driver.findElement(By.cssSelector(".export > .btn")).click();
    driver.findElement(By.linkText("CSV")).click();
  }
}
